version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - 3001:3001
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    container_name: PostrgesDB
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - mdz-postgres:/var/lib/postgresql/data

volumes:
  mdz-postgres:
